# Generated by Django 2.0.6 on 2018-08-19 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metadatatype',
            name='type',
            field=models.CharField(choices=[('decimal', 'decimal'), ('integer', 'integer'), ('varchar', 'varchar')], max_length=200),
        ),
    ]
