# Generated by Django 2.0.6 on 2018-08-19 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0002_auto_20180819_1016'),
    ]

    operations = [
        migrations.AddField(
            model_name='metadatatype',
            name='unit',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
